# -*- coding: utf-8 -*-
"""Twitter Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zC9AwiGcpmxnts1XU6o2XJgQgCu-TJLD

# Sentiment Analysis with LSTM-CNN Hybrid Model

## 1. Load and Prepare Labeled Training Data (`twitter_training.csv`)

This section loads the `twitter_training.csv` dataset, which contains pre-labeled tweets (negative, neutral, positive). We'll perform essential preprocessing steps, including cleaning text, mapping sentiment labels to numerical values, tokenizing the text, and padding sequences to a uniform length. Finally, the data will be split into training and testing sets for model development.
"""

import pandas as pd
import os
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from sklearn.model_selection import train_test_split

# --- NLTK Downloads and Preprocessing Function ---
# Download NLTK data (if not already downloaded)
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)

# Initialize NLTK tools
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    # 1. Convert to lowercase
    text = text.lower()

    # 2. Remove URLs (http/https links)
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    # Remove mentions (@username)
    text = re.sub(r'@\w+', '', text)
    # Remove hashtags (#hashtag) - keeping the word if desired, here we remove the #
    text = re.sub(r'#\w+', '', text)

    # 3. Remove punctuation and special characters
    text = re.sub(r'[^a-zA-Z\s]', '', text) # Keep only letters and spaces

    # 4. Tokenize and remove stopwords and lemmatize
    tokens = nltk.word_tokenize(text)
    processed_tokens = []
    for word in tokens:
        if word not in stop_words and len(word) > 1: # Remove stopwords and single characters (often punctuation remnants)
            processed_tokens.append(lemmatizer.lemmatize(word))

    # Join tokens back into a string
    text = ' '.join(processed_tokens)

    return text

# --- Global Configuration Parameters ---
MAX_VOCAB_SIZE = 20000  # Max number of unique words to keep for tokenizer
MAX_SEQUENCE_LENGTH = 100 # Max length of each tweet sequence after padding
EMBEDDING_DIM = 100 # Dimension of the word embeddings
TEST_SIZE = 0.2 # Percentage of data to be used for testing in train_test_split
RANDOM_STATE = 42 # For reproducibility of data splitting

print("NLTK resources loaded, preprocessing function and global parameters defined.")

# --- Load twitter_training.csv ---
# Define the directory path (adjust if different)
data_raw_path = '/content/drive/MyDrive/Kuliah/Skripsi/Data RAW'
twitter_training_path = os.path.join(data_raw_path, 'twitter_training.csv')

if os.path.exists(twitter_training_path):
    print(f"Loading {twitter_training_path}...")
    try:
        # Load without header and assign custom column names
        raw_training_df = pd.read_csv(twitter_training_path, header=None)
        raw_training_df.columns = ['tweet_id', 'entity', 'sentiment', 'full_text']

        print("Twitter training data loaded successfully!")
        print("Initial Info for twitter_training.csv:")
        raw_training_df.info()
        print("First 5 rows of twitter_training.csv:")
        display(raw_training_df.head())
    except Exception as e:
        print(f"Error loading twitter_training.csv: {e}")
        raw_training_df = pd.DataFrame() # Create empty DataFrame on error
else:
    print(f"File not found: {twitter_training_path}. Please ensure the file is in the specified path.")
    raw_training_df = pd.DataFrame() # Create empty DataFrame if file not found


# --- Preprocess Labeled Training Data ---
if not raw_training_df.empty:
    training_data_df = raw_training_df.copy()
    print("\nApplying preprocessing to the new training data...")

    # Handle duplicates
    initial_rows_train = len(training_data_df)
    training_data_df.drop_duplicates(inplace=True)
    print(f"Removed {initial_rows_train - len(training_data_df)} duplicate rows from training_data_df.")

    # Drop rows with null values in 'full_text'
    if 'full_text' in training_data_df.columns:
        initial_rows_non_null = len(training_data_df)
        training_data_df.dropna(subset=['full_text'], inplace=True)
        print(f"Removed {initial_rows_non_null - len(training_data_df)} rows with missing 'full_text' values.")
    else:
        print("Warning: 'full_text' column not found in training_data_df. Cannot perform null check.")
        training_data_df = pd.DataFrame() # Create empty DataFrame on error

    # Process sentiment labels
    if 'sentiment' in training_data_df.columns:
        print("\nUnique sentiment values BEFORE mapping:")
        print(training_data_df['sentiment'].unique())

        # Map sentiment categories to numerical labels (0: negative, 1: neutral, 2: positive)
        sentiment_mapping = {
            'negative': 0, 'neutral': 1, 'positive': 2,
            'Irrelevant': 1, # Treat 'Irrelevant' as neutral
            'Negative': 0, 'Positive': 2,
            'null': 1 # Treat 'null' sentiment as neutral
        }
        training_data_df['sentiment_label'] = training_data_df['sentiment'].map(sentiment_mapping)

        # Drop rows where sentiment mapping resulted in NaN
        if 'sentiment_label' in training_data_df.columns:
            initial_rows_mapped_sentiment = len(training_data_df)
            training_data_df.dropna(subset=['sentiment_label'], inplace=True)
            print(f"Removed {initial_rows_mapped_sentiment - len(training_data_df)} rows with unmappable sentiment labels.")
            training_data_df['sentiment_label'] = training_data_df['sentiment_label'].astype(int)
            print("Mapped 'sentiment' column to 'sentiment_label' (0: negative, 1: neutral/irrelevant, 2: positive). ")
            print("Sentiment label distribution:\n", training_data_df['sentiment_label'].value_counts())
        else:
            print("Warning: 'sentiment_label' column not created. Check 'sentiment' column presence and mapping logic.")
            training_data_df = pd.DataFrame() # Clear dataframe if sentiment labels are missing or mapping failed
    else:
        print("Warning: 'sentiment' column not found in twitter_training.csv. Cannot create sentiment_label.")
        training_data_df = pd.DataFrame() # Clear dataframe if sentiment labels are missing

    # Apply text preprocessing function to 'full_text'
    if 'full_text' in training_data_df.columns and not training_data_df.empty:
        print("Applying text preprocessing to 'full_text' column of training_data_df...")
        training_data_df['processed_text'] = training_data_df['full_text'].apply(preprocess_text)
        print("Text preprocessing complete for training_data_df.")
    else:
        print("Skipping text preprocessing as training_data_df is empty or 'full_text' column is missing.")

    print("\nUpdated Info for training_data_df after cleaning and preprocessing:")
    training_data_df.info()
    print("\nFirst 5 rows of training_data_df with 'processed_text' and 'sentiment_label' columns:")
    display(training_data_df[['full_text', 'processed_text', 'sentiment', 'sentiment_label']].head())

    # --- Tokenization, Sequencing, and Padding for Labeled Data ---
    tokenizer_labeled = Tokenizer(num_words=MAX_VOCAB_SIZE, oov_token="<unk>")
    print(f"\nFitting tokenizer on {len(training_data_df['processed_text'])} labeled texts...")
    tokenizer_labeled.fit_on_texts(training_data_df['processed_text'])

    sequences_labeled = tokenizer_labeled.texts_to_sequences(training_data_df['processed_text'])
    padded_sequences_labeled = pad_sequences(sequences_labeled, maxlen=MAX_SEQUENCE_LENGTH, padding='post', truncating='post')

    print("Tokenization, sequencing, and padding complete for labeled data.")
    VOCAB_SIZE_LABELED = len(tokenizer_labeled.word_index) + 1 # +1 for OOV token
    print(f"\nVocabulary size for labeled data: {VOCAB_SIZE_LABELED}")
    print(f"Shape of padded labeled sequences: {padded_sequences_labeled.shape}")

    # --- Data Splitting for Labeled Data ---
    X_labeled = padded_sequences_labeled
    y_labeled = training_data_df['sentiment_label'].values

    X_train_labeled, X_test_labeled, y_train_labeled, y_test_labeled = train_test_split(
        X_labeled, y_labeled, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y_labeled)

    print("\nData split into training and testing sets complete for labeled data.")
    print(f"Shape of X_train_labeled: {X_train_labeled.shape}")
    print(f"Shape of X_test_labeled: {X_test_labeled.shape}")
    print(f"Shape of y_train_labeled: {y_train_labeled.shape}")
    print(f"Shape of y_test_labeled: {y_test_labeled.shape}")
else:
    print("Skipping processing labeled training data as raw_training_df is empty or not loaded.")

"""## 2. Load and Prepare Unlabeled Scraped Data (`Scrape (1-14).csv`)

This section will load all `Scrape (X).csv` files from `Scrape (1)` to `Scrape (14)`, concatenate them into a single DataFrame, and apply the same text preprocessing steps used for the labeled data. Crucially, the same tokenizer (`tokenizer_labeled`) fitted on the labeled data will be used to ensure consistent numerical representation. The processed and padded sequences will then be ready for sentiment prediction.
"""

print("\n--- Loading and Preprocessing Scraped Data (Scrape 1-14) ---")

df_list = []
for i in range(1, 15): # Loop through files from Scrape (1) to Scrape (14)
    file_name = f'Scrape ({i}).csv'
    file_path = os.path.join(data_raw_path, file_name)

    if os.path.exists(file_path):
        try:
            df = pd.read_csv(file_path)
            df_list.append(df)
            print(f"Loaded {file_name}")
        except Exception as e:
            print(f"Error loading {file_name}: {e}")
    else:
        print(f"File not found: {file_name}")

if df_list:
    combined_df = pd.concat(df_list, ignore_index=True)
    print("All scrape files reloaded and combined successfully!")
else:
    combined_df = pd.DataFrame()
    print("No scrape files were loaded.")

# Re-apply duplicate removal
initial_rows_count = len(combined_df)
combined_df.drop_duplicates(inplace=True)
print(f"Removed {initial_rows_count - len(combined_df)} duplicate rows.")

# Re-apply dropping 'location' and 'username' columns, and convert 'created_at'
combined_df = combined_df.drop(columns=['location', 'username'], errors='ignore')
# Ensure 'created_at' column exists before converting
if 'created_at' in combined_df.columns:
    combined_df['created_at'] = pd.to_datetime(combined_df['created_at'], errors='coerce')
    print("Dropped 'location' and 'username' columns and converted 'created_at' to datetime.")
else:
    print("Warning: 'created_at' column not found. Skipping datetime conversion.")

# Re-apply language filtering
initial_rows_lang_filter = len(combined_df)
if 'lang' in combined_df.columns:
    combined_df = combined_df[combined_df['lang'] == 'en'].copy()
    print(f"Filtered out {initial_rows_lang_filter - len(combined_df)} non-English tweets.")
else:
    print("Warning: 'lang' column not found. Skipping language filtering.")

# Apply the preprocessing function to the 'full_text' column
if 'full_text' in combined_df.columns and not combined_df.empty:
    print("Applying text preprocessing to 'full_text' column of combined_df...")
    combined_df['processed_text'] = combined_df['full_text'].apply(preprocess_text)
    print("Text preprocessing complete for combined_df.")
else:
    print("Warning: 'full_text' column not found or combined_df is empty. Skipping preprocessing for combined_df.")

print("Combined DataFrame re-initialized and preprocessed.")
combined_df.info()

# --- Tokenization, Sequencing, and Padding for Scraped Data ---
# Ensure tokenizer_labeled was successfully created from the labeled data processing step
if 'tokenizer_labeled' in locals() and not combined_df.empty and 'processed_text' in combined_df.columns:
    print(f"\nUsing tokenizer (fitted on labeled data) for {len(combined_df['processed_text'])} texts from scraped data...")
    sequences_combined_for_prediction = tokenizer_labeled.texts_to_sequences(combined_df['processed_text'])
    padded_sequences_combined_for_prediction = pad_sequences(sequences_combined_for_prediction, maxlen=MAX_SEQUENCE_LENGTH, padding='post', truncating='post')

    print("Tokenization, sequencing, and padding complete for scraped data.")
    print(f"Shape of padded scraped sequences for prediction: {padded_sequences_combined_for_prediction.shape}")

    print("First 5 rows of combined_df with processed_text:")
    display(combined_df[['full_text', 'processed_text']].head())

else:
    print("Skipping tokenization/padding for scraped data as tokenizer_labeled is not available, combined_df is empty, or 'processed_text' is missing.")
    padded_sequences_combined_for_prediction = np.array([]) # Initialize as empty array

"""## 3. Build LSTM-CNN Hybrid Model

Here, we define a hybrid deep learning model that combines both Long Short-Term Memory (LSTM) and Convolutional Neural Network (CNN) layers. LSTMs are effective at capturing long-range dependencies in sequential data (like text), while CNNs are good at extracting local features (like n-grams). The model will use an embedding layer to represent words as dense vectors, followed by convolutional and LSTM layers, and finally a dense output layer for sentiment classification.
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Conv1D, GlobalMaxPooling1D, LSTM, Dense, Dropout, Bidirectional

if 'VOCAB_SIZE_LABELED' not in locals():
    VOCAB_SIZE_LABELED = MAX_VOCAB_SIZE + 1 # Fallback if not defined from labeled data processing

# Build the LSTM-CNN Hybrid model
print("Building LSTM-CNN Hybrid Model...")
hybrid_model = Sequential([
    Embedding(VOCAB_SIZE_LABELED, EMBEDDING_DIM, input_length=MAX_SEQUENCE_LENGTH, name="embedding_layer"),

    # CNN Part: Capture local features. Output is 3D (batch, timesteps, filters).
    Conv1D(filters=128, kernel_size=5, activation='relu', name="conv1d_layer"),
    # The GlobalMaxPooling1D layer is intentionally removed here to keep the output 3D
    # so it can be fed directly into the Bidirectional LSTM layer.

    # Dropout for regularization before LSTM
    Dropout(0.3, name="dropout_cnn"),

    # LSTM Part: Capture sequential dependencies. Expects 3D input.
    # Using Bidirectional LSTM for better context understanding
    Bidirectional(LSTM(64, return_sequences=False), name="bidirectional_lstm_layer"),
    Dropout(0.5, name="dropout_lstm"),

    # Output layer for 3 classes (negative, neutral, positive)
    Dense(3, activation='softmax', name="output_layer")
])

# Compile the model
hybrid_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

print("LSTM-CNN Hybrid Model Built and Compiled.")
hybrid_model.summary()

"""## 4.1 Hyperparameter Tuning with Keras Tuner

To further optimize our model, we'll use Keras Tuner to systematically search for the best combination of hyperparameters, such as the number of filters in `Conv1D` layers, units in `LSTM` layers, and dropout rates. This will help us find a model configuration that potentially yields better performance.
"""

import keras_tuner

# Define the model building function for Keras Tuner
def build_tunable_model(hp):
    model = Sequential([
        Embedding(VOCAB_SIZE_LABELED, EMBEDDING_DIM, input_length=MAX_SEQUENCE_LENGTH, name="embedding_layer"),

        # Tunable Conv1D Layer
        Conv1D(
            filters=hp.Int('filters', min_value=64, max_value=256, step=64),
            kernel_size=5, activation='relu', name="conv1d_layer"
        ),
        Dropout(hp.Float('dropout_cnn', min_value=0.2, max_value=0.5, step=0.1), name="dropout_cnn"),

        # Tunable Bidirectional LSTM Layer
        Bidirectional(LSTM(hp.Int('lstm_units', min_value=32, max_value=128, step=32), return_sequences=False), name="bidirectional_lstm_layer"),
        Dropout(hp.Float('dropout_lstm', min_value=0.3, max_value=0.6, step=0.1), name="dropout_lstm"),

        # Output layer
        Dense(3, activation='softmax', name="output_layer")
    ])

    # Tunable learning rate for the Adam optimizer
    learning_rate = hp.Choice('learning_rate', values=[1e-2, 1e-3, 1e-4])
    optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)

    model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

print("Tunable model building function defined.")

# Initialize the Keras Tuner (RandomSearch in this case)
tuner = keras_tuner.RandomSearch(
    build_tunable_model,
    objective='val_accuracy',
    max_trials=5,  # Number of different hyperparameter combinations to try
    executions_per_trial=1, # Number of models to train for each trial (for robustness)
    directory='keras_tuner_dir', # Directory to store results
    project_name='sentiment_hybrid_tuning'
)

print("Keras Tuner initialized. Starting search for best hyperparameters...")

# Run the hyperparameter search
# Use a small number of epochs for tuning to speed up the process
tuner.search(X_train_labeled, y_train_labeled, epochs=3, validation_split=0.2, verbose=1)

print("Hyperparameter search complete.")

# Get the optimal hyperparameters
best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]
print(f"\nOptimal hyperparameters found:")
print(f"  Conv1D filters: {best_hps.get('filters')}")
print(f"  LSTM units: {best_hps.get('lstm_units')}")
print(f"  CNN dropout rate: {best_hps.get('dropout_cnn')}")
print(f"  LSTM dropout rate: {best_hps.get('dropout_lstm')}")
print(f"  Learning rate: {best_hps.get('learning_rate')}")

# Build the best model found by the tuner and assign it to hybrid_model
hybrid_model = tuner.get_best_models(num_models=1)[0]
print("\nBest model from Keras Tuner assigned to 'hybrid_model'.")

"""## 4. Train the Hybrid Model

Now, we will train the LSTM-CNN hybrid model using the `X_train_labeled` and `y_train_labeled` datasets. A portion of the training data will be used for validation during training to monitor the model's performance on unseen data and detect overfitting.
"""

if 'X_train_labeled' in locals() and 'y_train_labeled' in locals() and X_train_labeled.size > 0:
    print("\nTraining LSTM-CNN Hybrid Model...")
    hybrid_history = hybrid_model.fit(X_train_labeled, y_train_labeled,
                                      epochs=10, # You can adjust the number of epochs
                                      batch_size=32,
                                      validation_split=0.2, # Use 20% of training data for validation
                                      verbose=1)
    print("LSTM-CNN Hybrid Model training complete.")
else:
    print("Skipping model training: Labeled training data (X_train_labeled, y_train_labeled) is not available or is empty.")
    hybrid_history = None # Ensure hybrid_history is defined even if training is skipped

"""## 5. Evaluate the Hybrid Model

After training, we evaluate the hybrid model's performance on the `X_test_labeled` and `y_test_labeled` data. This step provides an unbiased assessment of how well the model generalizes to new, unseen labeled examples.
"""

if 'X_test_labeled' in locals() and 'y_test_labeled' in locals() and X_test_labeled.size > 0:
    print("\nEvaluating LSTM-CNN Hybrid Model on test data...")
    hybrid_loss, hybrid_accuracy = hybrid_model.evaluate(X_test_labeled, y_test_labeled, verbose=0)
    print(f"Hybrid Model Test Loss: {hybrid_loss:.4f}")
    print(f"Hybrid Model Test Accuracy: {hybrid_accuracy:.4f}")
    print("Hybrid Model evaluation complete.")
else:
    print("Skipping model evaluation: Labeled test data (X_test_labeled, y_test_labeled) is not available or is empty.")

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

if 'X_test_labeled' in locals() and 'y_test_labeled' in locals() and X_test_labeled.size > 0 and hybrid_model:
    print("\nGenerating confusion matrix for the test set...")

    # Get predictions for the test set
    y_pred_probs = hybrid_model.predict(X_test_labeled)
    y_pred = np.argmax(y_pred_probs, axis=1)

    # Calculate the confusion matrix
    cm = confusion_matrix(y_test_labeled, y_pred)

    # Define sentiment labels for plotting
    sentiment_labels = ['Negative', 'Neutral', 'Positive']

    # Plot the confusion matrix
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=sentiment_labels, yticklabels=sentiment_labels)
    plt.title('Confusion Matrix for LSTM-CNN Hybrid Model (Test Set)')
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.show()

    print("Confusion matrix generation complete.")
else:
    print("Skipping confusion matrix generation: Labeled test data (X_test_labeled, y_test_labeled) or model not available.")

import joblib

# Ensure hybrid_model is available. If the Keras Tuner cell was run, tuner should exist.
if 'tuner' in locals():
    try:
        hybrid_model = tuner.get_best_models(num_models=1)[0]
        print("Successfully retrieved 'hybrid_model' from tuner for saving.")
    except Exception as e:
        print(f"Warning: Could not retrieve hybrid_model from tuner: {e}")
        print("Please ensure the Keras Tuner cell (4.1) has been run successfully to define 'hybrid_model'.")
        hybrid_model = None
else:
    print("Error: 'tuner' object not found. Please ensure the Keras Tuner cell (4.1) has been run successfully.")
    hybrid_model = None


if hybrid_model is not None:
    # Save the trained model
    model_save_path = '/content/hybrid_sentiment_model.keras'
    hybrid_model.save(model_save_path)
    print(f"Hybrid model saved to {model_save_path}")
else:
    print("Skipping model saving as hybrid_model is not defined.")

# Save the tokenizer
if 'tokenizer_labeled' in locals():
    tokenizer_save_path = '/content/tokenizer_labeled.joblib'
    joblib.dump(tokenizer_labeled, tokenizer_save_path)
    print(f"Tokenizer saved to {tokenizer_save_path}")
else:
    print("Skipping tokenizer saving as tokenizer_labeled is not defined.")

"""## 7. Create Streamlit Application for Interactive Prediction

Now, we'll create the code for a Streamlit application (`app.py`) that will allow you to interactively predict sentiments. This application will:

1.  Load the pre-trained LSTM-CNN model and tokenizer.
2.  Provide an interface to input text for single tweet sentiment prediction.
3.  Allow uploading a CSV file containing tweets for batch sentiment prediction.
4.  Display the predicted sentiments and their distribution.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import tensorflow as tf
# from tensorflow.keras.preprocessing.sequence import pad_sequences
# import nltk
# from nltk.corpus import stopwords
# from nltk.stem import WordNetLemmatizer
# import re
# import joblib
# 
# # --- Global Configuration Parameters (must match training) ---
# MAX_SEQUENCE_LENGTH = 100 # Max length of each tweet sequence after padding
# 
# # --- NLTK Downloads and Preprocessing Function ---
# # NLTK Downloads (cache these for Streamlit)
# @st.cache_resource
# def download_nltk_data():
#     nltk.download('stopwords', quiet=True)
#     nltk.download('wordnet', quiet=True)
#     nltk.download('punkt', quiet=True)
#     nltk.download('punkt_tab', quiet=True)
#     return set(stopwords.words('english')), WordNetLemmatizer()
# 
# stop_words, lemmatizer = download_nltk_data()
# 
# def preprocess_text(text):
#     if not isinstance(text, str): # Handle non-string inputs (e.g., NaN)
#         return ""
#     text = text.lower()
#     text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
#     text = re.sub(r'@\w+', '', text)
#     text = re.sub(r'#\w+', '', text)
#     text = re.sub(r'[^a-zA-Z\s]', '', text)
#     tokens = nltk.word_tokenize(text)
#     processed_tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words and len(word) > 1]
#     return ' '.join(processed_tokens)
# 
# # --- Load Model and Tokenizer (cache these for Streamlit) ---
# @st.cache_resource
# def load_model_and_tokenizer(model_path, tokenizer_path):
#     try:
#         model = tf.keras.models.load_model(model_path)
#         tokenizer = joblib.load(tokenizer_path)
#         return model, tokenizer
#     except Exception as e:
#         st.error(f"Error loading model or tokenizer: {e}")
#         return None, None
# 
# model_path = '/content/hybrid_sentiment_model.keras'
# tokenizer_path = '/content/tokenizer_labeled.joblib'
# model, tokenizer = load_model_and_tokenizer(model_path, tokenizer_path)
# 
# sentiment_labels_map = {0: 'Negative', 1: 'Neutral', 2: 'Positive'}
# 
# # --- Streamlit UI ---
# st.title('Sentiment Analysis with LSTM-CNN Hybrid Model')
# st.write('Predict sentiment (Negative, Neutral, Positive) from text.')
# 
# if model is None or tokenizer is None:
#     st.error("Cannot proceed without loading the model and tokenizer.")
# else:
#     # Single Text Input Prediction
#     st.header('Single Text Prediction')
#     user_input = st.text_area('Enter text for sentiment prediction:', 'This product is amazing and I love it!')
#     if st.button('Predict Sentiment'):
#         if user_input:
#             processed_input = preprocess_text(user_input)
#             if processed_input:
#                 sequence = tokenizer.texts_to_sequences([processed_input])
#                 padded_sequence = pad_sequences(sequence, maxlen=MAX_SEQUENCE_LENGTH, padding='post', truncating='post')
#                 prediction_probs = model.predict(padded_sequence)
#                 predicted_label = np.argmax(prediction_probs)
#                 predicted_sentiment = sentiment_labels_map[predicted_label]
#                 confidence = prediction_probs[0][predicted_label] * 100
# 
#                 st.success(f"Predicted Sentiment: **{predicted_sentiment}** (Confidence: {confidence:.2f}%) ")
#                 st.write(f"Processed Text: {processed_input}")
#             else:
#                 st.warning("Input text could not be processed. Please try a different text.")
#         else:
#             st.warning("Please enter some text for prediction.")
# 
#     st.markdown('---')
# 
#     # CSV File Upload Prediction
#     st.header('Batch Prediction from CSV')
#     uploaded_file = st.file_uploader("Upload a CSV file containing a 'full_text' column", type=['csv'])
# 
#     if uploaded_file is not None:
#         try:
#             df_uploaded = pd.read_csv(uploaded_file)
#             st.write("Uploaded DataFrame head:")
#             st.dataframe(df_uploaded.head())
# 
#             if 'full_text' in df_uploaded.columns:
#                 st.info("Processing uploaded file...")
#                 df_uploaded['processed_text'] = df_uploaded['full_text'].apply(preprocess_text)
# 
#                 # Filter out rows where processed_text is empty after preprocessing
#                 df_to_predict = df_uploaded[df_uploaded['processed_text'].str.strip() != ''].copy()
# 
#                 if not df_to_predict.empty:
#                     sequences_uploaded = tokenizer.texts_to_sequences(df_to_predict['processed_text'])
#                     padded_sequences_uploaded = pad_sequences(sequences_uploaded, maxlen=MAX_SEQUENCE_LENGTH, padding='post', truncating='post')
# 
#                     batch_predictions = model.predict(padded_sequences_uploaded)
#                     df_to_predict['predicted_sentiment_label'] = np.argmax(batch_predictions, axis=1)
#                     df_to_predict['predicted_sentiment'] = df_to_predict['predicted_sentiment_label'].map(sentiment_labels_map)
# 
#                     st.success("Batch prediction complete!")
#                     st.write("Predicted sentiments for the first 10 rows:")
#                     st.dataframe(df_to_predict[['full_text', 'processed_text', 'predicted_sentiment']].head(10))
# 
#                     # Display distribution
#                     sentiment_counts = df_to_predict['predicted_sentiment'].value_counts().sort_index()
#                     st.subheader('Distribution of Predicted Sentiments in Uploaded Data')
#                     st.bar_chart(sentiment_counts)
# 
#                     csv_output = df_to_predict.to_csv(index=False).encode('utf-8')
#                     st.download_button(
#                         label="Download Predicted CSV",
#                         data=csv_output,
#                         file_name="predicted_sentiments.csv",
#                         mime="text/csv",
#                     )
#                 else:
#                     st.warning("No valid text found in the 'full_text' column after preprocessing for prediction.")
# 
#             else:
#                 st.error("The uploaded CSV must contain a column named 'full_text'.")
#         except Exception as e:
#             st.error(f"Error processing the uploaded file: {e}")

"""## 8. Run the Streamlit Application

To run the Streamlit application you just created, you'll need to:

1.  **Open a new terminal** in Google Colab (Go to `Runtime` -> `Open new tab` -> `Open terminal`).
2.  **Navigate to the directory** where `app.py` was saved (usually `/content/` if you used `%%writefile app.py`).
3.  **Run the command:** `streamlit run app.py & npx localtunnel --port 8501`

This command will start the Streamlit server and create a public URL using `localtunnel` which you can open in your web browser to interact with the application.

## 6. Predict Sentiments on Scraped Data

Finally, we use the trained LSTM-CNN hybrid model to predict sentiment labels for the preprocessed and padded scraped data (`combined_df`). The predicted sentiments will be added as a new column to `combined_df`, and we'll display the distribution of these predicted sentiments.
"""

import matplotlib.pyplot as plt
import seaborn as sns

if 'padded_sequences_combined_for_prediction' in locals() and padded_sequences_combined_for_prediction.size > 0 and 'combined_df' in locals() and not combined_df.empty:
    print("\nMaking sentiment predictions on combined_df using the hybrid model...")
    hybrid_predictions = hybrid_model.predict(padded_sequences_combined_for_prediction)

    # Get the predicted class (0, 1, or 2) by taking the argmax of the probabilities
    combined_df['predicted_sentiment'] = np.argmax(hybrid_predictions, axis=1)

    print("Sentiment prediction complete. Added 'predicted_sentiment' column to combined_df.")

    # Display the first few rows with the new predicted sentiment
    print("\nFirst 10 rows of combined_df with predicted sentiments:")
    display(combined_df[['full_text', 'processed_text', 'predicted_sentiment']].head(10))

    # Display the distribution of predicted sentiments
    print("\nDistribution of Predicted Sentiments in Scraped Data:")
    sentiment_labels_map = {0: 'Negative', 1: 'Neutral', 2: 'Positive'}
    predicted_sentiment_counts = combined_df['predicted_sentiment'].map(sentiment_labels_map).value_counts().sort_index()
    print(predicted_sentiment_counts)

    # Plot the distribution
    plt.figure(figsize=(8, 6))
    sns.barplot(x=predicted_sentiment_counts.index, y=predicted_sentiment_counts.values, palette='viridis', hue=predicted_sentiment_counts.index, legend=False)
    plt.title('Distribution of Predicted Sentiments in Scraped Data')
    plt.xlabel('Predicted Sentiment (0: Negative, 1: Neutral, 2: Positive)')
    plt.ylabel('Count')
    plt.xticks(ticks=[0, 1, 2], labels=['Negative', 'Neutral', 'Positive'])
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()
else:
    print("Skipping sentiment prediction: Scraped data (padded_sequences_combined_for_prediction or combined_df) not available or empty.")
